#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jun 11 16:14:45 +07 2025
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim cpurisc_program_counter_tb_behav -key {Behavioral:sim_1:Functional:cpurisc_program_counter_tb} -tclbatch cpurisc_program_counter_tb.tcl -view /home/kien/Documents/Workspace/Simple_RISC_CPU/project_risc_cpu/project_risc_cpu.wcfg/cpurisc_program_counter_tb_behav.wcfg -log simulate.log"
xsim cpurisc_program_counter_tb_behav -key {Behavioral:sim_1:Functional:cpurisc_program_counter_tb} -tclbatch cpurisc_program_counter_tb.tcl -view /home/kien/Documents/Workspace/Simple_RISC_CPU/project_risc_cpu/project_risc_cpu.wcfg/cpurisc_program_counter_tb_behav.wcfg -log simulate.log

